### ISSUE TITLE
Discussion: Set Drvfs metadata support from user mode

### ISSUE THREAD

**Issue by Biswa96** [0xbadfca11/lxsstat#6]
Continuing discussion from commit https://github.com/0xbadfca11/lxsstat/commit/025e8813f316f8da1ff5ff45e641b84ffcc23666 : 

I've found thoose extended attributes (EA) in LxCore.sys driver. Those are configured with `ZwSetEaFile()` but the buffer length is `84` bytes. Here is a screenshot of LxCore driver in IDA:

![extended_attributes](https://user-images.githubusercontent.com/31443074/39081070-5c90ca7a-4558-11e8-8efc-747b9aab90ef.PNG)

I mount D:\ drive with `mount -o metadata,uid=1000,gid=1000` but I can't get those EA in `ZwQueryEaFile()`. Can you provide some details about how can I get/query those EA with `ZwQueryEaFile()` with STATUS_SUCCESS?

**Comment by Biswa96** [comment]
One naive question, why do you allocate maximum memory of UCHAR/USHORT in `MAXIMUM_LENGTH_OF_EA_NAME` and `MAXIMUM_LENGTH_OF_EA_VALUE`? `NtQueryEaFile()` can query those EA values with smaller required memory as follows:

```
size_t Length = sizeof(FILE_FULL_EA_INFORMATION) + strlen(eaName) + eaValueLength;
FILE_FULL_EA_INFORMATION* Buffer = (FILE_FULL_EA_INFORMATION*)malloc(Length);

size_t EaListLength = sizeof(FILE_GET_EA_INFORMATION) + strlen(eaName);
FILE_GET_EA_INFORMATION* EaList = (FILE_GET_EA_INFORMATION*)malloc(EaListLength);
    
//Copy attributes

NtQueryEaFile(handle, &IoStatusBlock, Buffer, Length, FALSE, EaList, EaListLength, NULL, TRUE);
```

I've tried to apply those EA ($LXUID, $LXGID) with `NtSetEaFile()` but it shows error `0x8000014`. I'll try again. And there is another FOSS tool to view EA [FileTest](https://github.com/ladislav-zezula/FileTest). Helpful for @DDoSolitary https://github.com/DDoSolitary/LxRunOffline/issues/36

**Comment by 0xbadfca11** [comment]
There is no particularly important reason. In the future, I thought that it would be troublesome if the required buffer size changed. I'm lazy.

**Comment by Biswa96** [comment]
That one byte is not a problem during `NtSetEaFile()`. But I've found some interesting fact with your provided link and NTFS Stream Explorer program. 

`NtQueryEaFile()` can provides all the EA without iterating all the EA values (like in lxsstat.cpp). I've just set `RestartScan =TRUE` and `ReturnSingle = FALSE` in that function and Buffer spits out all three EaName and EaValue. Also `EaLength` can be known from `NtQueryFileInformation()` and allocated dynamically.
 
After `mount -o metadata` command, I found that LxCore.sys sets those three EA simultaneously without `chmod` and `chown` commands. Did you find the `$LXDEV` attribute in any file?

**Comment by 0xbadfca11** [comment]
``$LXDEV`` is added to the device file created by ``mknod`` command or ``mkfifo`` command.

**Comment by Biswa96** [comment]
Is there any security mechanism in kernel that restricts any arbritary extended attributes to be added with a file?

**Comment by 0xbadfca11** [comment]
I only know deny FILE_WRITE_EA of NTFS ACL.
I have never heard of a policy to deny permission by the name of EA or to enforce per-process.

**Comment by Biswa96** [comment]
I've successfully ad those three metadata from user mode with `NtSetEaFile()`. Closing this discussion..... Thank You!

**Comment by Biswa96** [comment]
Is there any relation with `$MFT` file and Extended Attributes? I add `LXATTRB` and other three EAs with `NtSetEaFile()` in a VHD file. Then I unmount that VHD, extract `$MFT` with 7ZIP and open that file in HxD HexEditor. The screenshot is as follow:

![mft_lxattrb](https://user-images.githubusercontent.com/31443074/39491694-cff56bba-4daa-11e8-86a9-07b73d07683b.PNG)

**Comment by 0xbadfca11** [comment]
Have you heard that NTFS stores very small data directly in the MFT?
This is not limited to user data, it also applies to all metadata including extended attributes.

**Comment by Biswa96** [comment]
Did you see any change/improvement in configuring DRVFS metadata in build 17666? In that build LxssManager.dll has those extended attributes.

**Comment by 0xbadfca11** [comment]
I don't know.
